/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jian/catkin_ws/src/crr_robot_controller/srv/crrCtrl.srv
 *
 */


#ifndef CRR_ROBOT_CONTROLLER_MESSAGE_CRRCTRLREQUEST_H
#define CRR_ROBOT_CONTROLLER_MESSAGE_CRRCTRLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crr_robot_controller
{
template <class ContainerAllocator>
struct crrCtrlRequest_
{
  typedef crrCtrlRequest_<ContainerAllocator> Type;

  crrCtrlRequest_()
    : direction(0)
    , mode(0)  {
    }
  crrCtrlRequest_(const ContainerAllocator& _alloc)
    : direction(0)
    , mode(0)  {
    }



   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef uint8_t _mode_type;
  _mode_type mode;




  typedef boost::shared_ptr< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct crrCtrlRequest_

typedef ::crr_robot_controller::crrCtrlRequest_<std::allocator<void> > crrCtrlRequest;

typedef boost::shared_ptr< ::crr_robot_controller::crrCtrlRequest > crrCtrlRequestPtr;
typedef boost::shared_ptr< ::crr_robot_controller::crrCtrlRequest const> crrCtrlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crr_robot_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'crr_robot_controller': ['/home/jian/catkin_ws/src/crr_robot_controller/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705346ba406dd3cf9e01f15a21777279";
  }

  static const char* value(const ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705346ba406dd3cfULL;
  static const uint64_t static_value2 = 0x9e01f15a21777279ULL;
};

template<class ContainerAllocator>
struct DataType< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crr_robot_controller/crrCtrlRequest";
  }

  static const char* value(const ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 direction\n\
uint8 mode\n\
";
  }

  static const char* value(const ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct crrCtrlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crr_robot_controller::crrCtrlRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRR_ROBOT_CONTROLLER_MESSAGE_CRRCTRLREQUEST_H
